version: '1'
services:
  client:
    build:
      context: ./client
    ports:
      - "8081:8081"
    image: client-image
    container_name: client-container
    stdin_open: true
    tty: true
    networks:
      - local

  server:
    build:
      context: ./server
    ports:
      - "8082:8082"
    image: server-image
    container_name: server-container
    stdin_open: true
    tty: true
    networks:
      - local

  h2memdb:
    build:
      context: ./h2memdb
    ports:
      - "8083:8083"
    image: h2memdb-image
    container_name: h2memdb-container
    stdin_open: true
    tty: true
    networks:
      - local

networks:
  local:
    driver: bridge